### PR TITLE
Update cap_sasl.pl

### PR DESCRIPTION
**Pull request by grawity**
This updates the Irssi implementation to 1.6 from Atheme's `contrib/cap_sasl.pl`, and turns it from a standalone script into an example snippet so that people don't actually use it. (1.8 in contrib has a better, native-Perl implementation.)

### CODE REVIEW

**Comment by Mikaela** [comment]
https://freenode.net/sasl/sasl-irssi.shtml links there.

**Comment by kaniini** [comment]
They should use the version on scripts.irssi.org instead.

**Comment by Mikaela** [comment]
* https://github.com/freenode/www/issues/1
* pr: https://github.com/freenode/www/pull/3

**Comment by comjf** [comment]
@Mikaela Just a note, this breaks the guide in https://wdtz.org/freenode-sasl-upgrade-irssi-howto.html

Is that guide no longer relevant?

**Comment by Mikaela** [comment]
@comjf I am not irssi user and I imagine other guides than http://freenode.net/kb/answer/irssi to be irrelevant and I also think that as irssi has finally started supporting SASL natively, the whole script is more or less irrelevant.

**Pull request merged**
